### ISSUE TITLE
Refactor from deployment to cronjob

### ISSUE THREAD

**Issue by onmomo** [trondhindenes/ecr-updater#12]
The project could leverage the K8s CronJob  to do the scheduling. This would simplify the code and optimize the K8s resource usage.

eg

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-credentials-updater
spec:
  schedule: "* */3 * * *" # ecr token expires every 12 hours, we try every 3 hours to refresh the token
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
...
```
